export {
  AladinBookWireSchema,
  AladinBooksResponseSchema,
  BookSearchPageSchema,
  BookReviewResponseSchema,
  EmbeddingResponseSchema,
  GoogleBooksPayloadSchema,
  KeywordsResponseSchema,
  NoteStructureSchema,
  RecallHistoryRowSchema,
  RecallSearchResponseSchema,
  ReadingInsightsResponseSchema,
  VisionOcrResponseSchema,
  type AladinBooksResponse,
  type BookReviewResponse,
  type BookSearchPage,
  type EmbeddingResponse,
  type GoogleBooksPayload,
  type KeywordsResponse,
  type NoteStructure,
  type ReadingInsightsResponse,
  type VisionOcrResponse,
} from "./contracts";
export {
  defaultFunctionTimeoutMs,
  invokeFunction,
  invokeProductFunction,
  invokeProductFunctionForSession,
  isFunctionsHttpError,
  parseFunctionResponse,
  type ProductFunctionOptions,
} from "./functions";
export { getProviderConfig, type ProviderConfig } from "./provider-config";
export {
  mapAdapterError,
  readAdapterErrorPayload,
  type AdapterErrorPayload,
} from "./errors";
export {
  searchAladinBooks,
  searchBooks,
  searchGoogleBooks,
} from "./book-search";
export {
  generateBookReview,
  generateEmbedding,
  generateReadingInsights,
  extractKeywords,
  normalizeRecallResponse,
  recommendNextBooks,
  runVisionOcr,
  searchRecall,
  structureNotes,
  type AdapterOptions,
  type EmbeddingInput,
  type OcrInput,
} from "./functions-adapters";
export {
  getConsent,
  getLatestRecommendation,
  getNoteStructure,
  deleteRecallHistory,
  listBookRecallHistory,
  listBookRecallHistoryPage,
  invokeProductRpc,
  listGlobalRecallHistory,
  listGlobalRecallHistoryPage,
  listOwnedBookImages,
  listRecallHistory,
  readBookImages,
  readNoteStructure,
  readRecallHistory,
  type ConsentRecord,
  type RecommendationCache,
  type TableOptions,
} from "./tables";
export {
  assertOwnedBookImagePath,
  defaultSignedUrlTtlSeconds,
  downloadOwnedBookImage,
  downloadPrivateBookImage,
  getBookImageUrl,
  listOwnedBookImagePaths,
  listPrivateBookImagePaths,
  ownedBookImagePath,
  privateBookImagesBucket,
  removeOwnedBookImagePaths,
  removePrivateBookImagePaths,
  refreshBookImageUrl,
  signedUrlRefreshSkewSeconds,
  uploadBookImage,
  uploadPrivateBookImage,
  type BookImagePathResult,
  type PrivateBookImageBytes,
  type SignedBookImageOptions,
  type SignedBookImageUrl,
  type SignedUrlCache,
  type StorageUploadBody,
  type UploadBookImageInput,
  type UploadedBookImage,
} from "./storage";
